### ISSUE TITLE
AndDiscoveryProviderSucceed: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled.

### ISSUE THREAD

**Issue by MichaellW23** [reqnroll/Reqnroll.VisualStudio#51]
### Used Visual Studio

Visual Studio 2022

### Are the latest Visual Studio updates installed?

Yes

### Content of reqnroll.json (if present)

{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "bindingAssemblies": [
    { "assembly": "E2E_****" },
    { "assembly": "E2E_****" },
    { "assembly": "E2E_WindowsPerformanceMonitor" }
  ],
  "trace": {
    "stepDefinitionSkeletonStyle": "RegexAttribute"
  }
}

### Issue Description

The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 

### Steps to Reproduce

Open the solution. 

Full output from Reqnroll: 
Info: OnActivityStarted: Starting Visual Studio Extension...
Info: CreateProjectScope: Initializing project: AlignRT_E2E_Tests
Info: OnSettingsInitialized: Project settings initialized: .NETCoreApp,Version=v8.0,Reqnroll:1.0.1,x64
Warning: AndDiscoveryProviderSucceed: Error during binding discovery. 
Command executed:
  D:\Repos\alignrt\E2ETests\AlignRT_E2E_Tests\bin\Debug\net8.0-windows> C:\Program Files\dotnet\dotnet.exe exec c:\users\mweclewski\appdata\local\microsoft\visualstudio\17.0_558bcd40\extensions\epq1gj5d.qkd\Connectors\Reqnroll-Generic-net8.0\reqnroll-vs.dll discovery D:\Repos\alignrt\E2ETests\AlignRT_E2E_Tests\bin\Debug\net8.0-windows\AlignRT_E2E_Tests.dll D:\Repos\alignrt\E2ETests\AlignRT_E2E_Tests\reqnroll.json
Exit code: 0
Message: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Reqnroll.Infrastructure.ContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at Reqnroll.Bindings.Provider.BindingProviderService.CreateGlobalContainer(Assembly testAssembly, String jsonConfiguration)
   at Reqnroll.Bindings.Provider.BindingProviderService.DiscoverBindings(Assembly testAssembly, String jsonConfiguration)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ReqnrollConnector.ReflectionExtensions.ReflectionCallStaticMethod[T](Type type, String methodName, Type[] parameterTypes, Object[] args) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\ReflectionExtensions.cs:line 43
   at ReqnrollConnector.ReqnrollProxies.BindingRegistryFactory.GetBindingRegistry(AssemblyLoadContext assemblyLoadContext, Assembly testAssembly, Option`1 configFile) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\ReqnrollProxies\BindingRegistryFactory.cs:line 17
   at ReqnrollConnector.Discovery.ReqnrollDiscoverer.Discover(IBindingRegistryFactory bindingRegistryFactory, AssemblyLoadContext assemblyLoadContext, Assembly testAssembly, Option`1 configFile) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\Discovery\ReqnrollDiscoverer.cs:line 28
   at ReqnrollConnector.Discovery.DiscoveryCommand.<>c__DisplayClass6_0.<Execute>b__0(IBindingRegistryFactory bindingRegistryFactory) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\Discovery\DiscoveryCommand.cs:line 27
   at FunctionalExtensions.Map[TSource,TResult](TSource this, Func`2 fn) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\FunctionalExtensions.cs:line 5
   at ReqnrollConnector.Discovery.DiscoveryCommand.Execute(AssemblyLoadContext assemblyLoadContext) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\Discovery\DiscoveryCommand.cs:line 25
   at ReqnrollConnector.ReflectionExecutor.<>c__DisplayClass3_0.<Execute>b__6(DiscoveryCommand cmd) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\ReflectionExecutor.cs:line 84
   at FunctionalExtensions.Map[TSource,TResult](TSource this, Func`2 fn) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\FunctionalExtensions.cs:line 5
   at ReqnrollConnector.ReflectionExecutor.<>c__DisplayClass3_1.<Execute>b__2() in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\ReflectionExecutor.cs:line 82
   at EitherAdapters.Try[T](Func`1 act) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\Either\EitherAdapters.cs:line 40
Info Found V1.0.0 at D:\Repos\alignrt\E2ETests\AlignRT_E2E_Tests\bin\Debug\net8.0-windows\Reqnroll.dll
Info Chosen BindingRegistryFactoryVLatest for 100000
Error System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Reqnroll.Infrastructure.ContainerBuilder.CreateGlobalContainer(Assembly testAssembly, IRuntimeConfigurationProvider configurationProvider)
   at Reqnroll.Bindings.Provider.BindingProviderService.CreateGlobalContainer(Assembly testAssembly, String jsonConfiguration)
   at Reqnroll.Bindings.Provider.BindingProviderService.DiscoverBindings(Assembly testAssembly, String jsonConfiguration)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at ReqnrollConnector.ReflectionExtensions.ReflectionCallStaticMethod[T](Type type, String methodName, Type[] parameterTypes, Object[] args) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\ReflectionExtensions.cs:line 43
   at ReqnrollConnector.ReqnrollProxies.BindingRegistryFactory.GetBindingRegistry(AssemblyLoadContext assemblyLoadContext, Assembly testAssembly, Option`1 configFile) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\ReqnrollProxies\BindingRegistryFactory.cs:line 17
   at ReqnrollConnector.Discovery.ReqnrollDiscoverer.Discover(IBindingRegistryFactory bindingRegistryFactory, AssemblyLoadContext assemblyLoadContext, Assembly testAssembly, Option`1 configFile) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\Discovery\ReqnrollDiscoverer.cs:line 28
   at ReqnrollConnector.Discovery.DiscoveryCommand.<>c__DisplayClass6_0.<Execute>b__0(IBindingRegistryFactory bindingRegistryFactory) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\Discovery\DiscoveryCommand.cs:line 27
   at FunctionalExtensions.Map[TSource,TResult](TSource this, Func`2 fn) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\FunctionalExtensions.cs:line 5
   at ReqnrollConnector.Discovery.DiscoveryCommand.Execute(AssemblyLoadContext assemblyLoadContext) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\Discovery\DiscoveryCommand.cs:line 25
   at ReqnrollConnector.ReflectionExecutor.<>c__DisplayClass3_0.<Execute>b__6(DiscoveryCommand cmd) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\ReflectionExecutor.cs:line 84
   at FunctionalExtensions.Map[TSource,TResult](TSource this, Func`2 fn) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\FunctionalExtensions.cs:line 5
   at ReqnrollConnector.ReflectionExecutor.<>c__DisplayClass3_1.<Execute>b__2() in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\ReflectionExecutor.cs:line 82
   at EitherAdapters.Try[T](Func`1 act) in D:\a\Reqnroll.VisualStudio\Reqnroll.VisualStudio\Connectors\Reqnroll.VisualStudio.ReqnrollConnector.Generic\NetExtensions\Either\EitherAdapters.cs:line 40
Warning: AndDiscoveryProviderSucceed: The project bindings (e.g. step definitions) could not be discovered. Navigation, step completion and other features are disabled. 
  Please check the error message above and report to https://github.com/reqnroll/Reqnroll.VisualStudio/issues if you cannot fix.

**Comment by MichaellW23** [comment]
Same thing I updated all the possible packages like Reqnroll, Cucumber etc.

**Comment by gasparnagy** [comment]
@MichaellW23 I suspect that there are some dependencies in any of the related projects that cause somehow the problem, but without diagnosing the concrete setup it is not really possible to fix this. 

Could you please try to make some repro project that shows the problem? Try so setup some ~empty projects first with the same dependencies and target frameworks as yours and let's hope that can reproduce the problem.

Another question: besides the VS problem can you run your tests? I mean do you see any assembly load errors when you actually run the tests?

**Comment by MichaellW23** [comment]
No, there is no problem with running tests.

**Comment by MichaellW23** [comment]
All the dependencies in the project: 
![image](https://github.com/user-attachments/assets/b3cff47e-7c05-4a74-b6a7-2c8720c8a037)

**Comment by gasparnagy** [comment]
@MichaellW23 I see you have a lot. But please optimize the process by trying to reproduce the issue yourself with a minimalistic project.

**Comment by MichaellW23** [comment]
The problem was the lack of System.Configuration.ConfigurationManager nuget package @gasparnagy

**Comment by MichaellW23** [comment]
The problem was resolved by updating Gherkin and Reqnroll packages somehow, what did not fixed the problem in first try, but everything is working fine for now.
